### ISSUE TITLE
Refresh doesn't remove items from file list.

### ISSUE THREAD

**Issue by simotek** [DaveMDS/egitu#2]
1. Modify a file
2. Open egitu
3. Manually remove file modifications
4. Refesh egitu
5. File with no changes is still in the list.

Again pretty minor not a blocking issue

**Comment by DaveMDS** [comment]
I cannot reproduce this issue here
can you double check that is broken for you? 
maybe you get some python errors on console when this occur?

**Comment by simotek** [comment]
I can't replicate this today, maybe its the fault of a NFS server.

**Comment by DaveMDS** [comment]
ok, then I'm closing this, please reopen if you see it again
